Develop
vladislavStel/java-filmorate-team-project pull request #10
Opened 2023-05-29 12:19 UTC by vladislavStel

2023-05-31 04:14 UTC, sergeymamonov requested changes
IncorrectParameterException - почему бы не воспользоваться аннотацией Lombok для геттера.

2023-05-31 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void deleteFilmById(@PathVariable("id") Long filmID) {
filmID исправить в соответствии со camelCase на filmId. Проверить по всему коду.

2023-05-31 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
Строка 27 getUserByID - несоблюдение camelCase.

2023-05-31 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                        .filter((film) -> film.getGenres().contains(genreStorage.findGenreById(genreId)))
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-05-31 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +                Set<Long> likesListByOtherUser = userStorage.findLikeListByUserId(otherUserId);
Здесь и ниже запросы к БД в цикле. От запросов к БД в цикле нужно избавиться.

2023-05-31 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +            filmsIdRecommended.forEach(filmId -> result.add(filmService.getFilmById(filmId)));
Запросы к БД в цикле.

2023-05-31 04:14 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    content varchar not null ,
Размер varchar должен быть ограничен.

2023-06-01 13:51 UTC, sergeymamonov approved these changes

2023-06-01 13:51 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      void addLike(Long filmID, Long userID);
Исправить имена параметров в соответствии с camelCase.

2023-06-01 13:51 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      void removeLike(Long filmID, Long userID);
Исправить имена параметров в соответствии с camelCase.

2023-06-01 13:51 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +    private List<Film> getPopularFilmsSorted(int count, int genreId, int year) {
Обычно располагаю сначала публичные поля (методы) в классе, а потом приватные.

2023-06-01 15:22 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +    private List<Film> getPopularFilmsSorted(int count, int genreId, int year) {
Все устранено.

2023-06-01 17:39 UTC, merged