Team Project.Added reviews to project.
vladislavStel/java-filmorate-team-project pull request #4
Opened 2023-05-25 15:46 UTC by Nevisky

Added reviews to project.

2023-05-26 09:23 UTC, vladislavStel requested changes

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler
Предлагаю вместе 2-х новых exception использовать обобщенный ObjectNotFoundException. И не придется использовать 2 лишних класса

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review upadteReview(@Valid @RequestBody Review review) {
имя метода написано с ошибкой

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviewService.upadateReview(review);
аналогичная ошибка

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void removeReview(@PathVariable("id") long id) {
предлагаю назвать deleteReview

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review findReviewById(@PathVariable("id") long id) {
этот метод лучше назнать getReviewById, т.к. методы find используются в репозиториях.

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Collection<Review> getAllReviewsByIdFilm(@RequestParam(required = false) Long filmId, @RequestParam(defaultValue = "10", required = false) int count) {
Может стоит использовать List?

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
Удали лишнюю строку

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class
Добавлен не нужный переход на новую строку

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectFieldReviewException.java
> +package ru.yandex.practicum.filmorate.exception;
Предлагаю убрать

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectReviewLikeException.java
> +package ru.yandex.practicum.filmorate.exception;
Аналогично

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    long reviewId;
Для reviewId лучше поставить аннотацию @Positive

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NotNull
@positive и notnull не потребуется

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NotNull
@positive

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +        if (review.getUserId() == null || review.getFilmId() == null) {
Если @positive будет у этих полей в классе Review, то данная проверка не требуется.

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +    public Review upadateReview(Review review) {
Ошибка в имени метода.

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        String sqlSaveReview = "INSERT INTO REVIEW (CONTENT, IS_POSITIVE, USER_ID, FILM_ID, USEFUL) VALUES (?,?,?,?,?)";
Прошу соблюдать кодстайл. в sql - Команды и названия таблиц - большими, а поля таблиц - маленькими

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +            review = Review.builder().reviewId(updateSet.getInt("review_id")).content(updateSet.getString("content")).isPositive(updateSet.getBoolean("is_positive")).userId(updateSet.getLong("user_id
Прошу выровнять

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +    public Review saveReview(Review review) {
назови метод просто save

его можно было бы реализовать через PreparedStatement и полученный Id передать в метод findById, тогда от одного select избавимся.

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +    public Collection<Review> getAllReviewsByFilmId(Long filmId, Integer count) {
назови метод findAllReviewByFilmId

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        return Review.builder().reviewId(rs.getLong("review_id")).content(rs.getString("content")).isPositive(rs.getBoolean("is_positive")).userId(rs.getLong("user_id")).filmId(rs.getLong("film_id"))
Выровняй пожалуйста

2023-05-26 09:23 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +
Удали лишние строки

2023-05-26 09:23 UTC, vladislavStel commented on src/main/resources/schema.sql
> +    content varchar not null ,
NOT NULL и далее также напиши

2023-05-26 10:00 UTC, vladislavStel requested changes

2023-05-26 10:00 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +            review = Review.builder().reviewId(updateSet.getInt("review_id")).content(updateSet.getString("content")).isPositive(updateSet.getBoolean("is_positive")).userId(updateSet.getLong("user_id
Предлагаю вместе повтора Review.builder несколько раз в разных методах, создать отдельный метод mapRowToReview  который принимает ResultSet и rowNum и возвращает скомпилированный Review.builder

2023-05-26 10:00 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        String sqlReviewsQuery = "SELECT * FROM REVIEW WHERE REVIEW_ID = ?";
Здесь можно избавиться от SELECT запроса, просто вызвав метод findById с полученным Id

2023-05-26 10:18 UTC, vladislavStel requested changes

2023-05-26 10:18 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        } else {
Данные проверки можно оптимизировать с помощью метода  аналогичного этому:
@Override
    public boolean isNotExistsUser(Long id) {
        SqlRowSet userRows = jdbcTemplate.queryForRowSet("SELECT * FROM USERS WHERE user_id = ?", id);
        return !userRows.next();
    }
его можно добавить в данный класс и вызывать когда нужна проверка наличия информации по Id? посмотри как это реализовано в UserDbStorage например. и проверку лаконичнее проводить не через if-else, а просто через if

2023-05-27 11:34 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler
Исправил

2023-05-27 11:38 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review upadteReview(@Valid @RequestBody Review review) {
Исправил

2023-05-27 11:39 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviewService.upadateReview(review);
Исправил

2023-05-27 11:39 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void removeReview(@PathVariable("id") long id) {
Исправил

2023-05-27 11:40 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review findReviewById(@PathVariable("id") long id) {
Исправил

2023-05-27 14:33 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Collection<Review> getAllReviewsByIdFilm(@RequestParam(required = false) Long filmId, @RequestParam(defaultValue = "10", required = false) int count) {
Исправил

2023-05-27 14:34 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
Исправил

2023-05-27 14:35 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class
Исправил

2023-05-27 14:35 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectFieldReviewException.java
> +package ru.yandex.practicum.filmorate.exception;
удалил

2023-05-27 14:36 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectReviewLikeException.java
> +package ru.yandex.practicum.filmorate.exception;
удалил

2023-05-27 14:37 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NotNull
удалил

2023-05-27 14:38 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NotNull
добавил

2023-05-27 14:39 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +    public Review upadateReview(Review review) {
исправил

2023-05-27 14:39 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +    public Review saveReview(Review review) {
Переписал метод

2023-05-27 14:39 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        String sqlSaveReview = "INSERT INTO REVIEW (CONTENT, IS_POSITIVE, USER_ID, FILM_ID, USEFUL) VALUES (?,?,?,?,?)";
Исправил

2023-05-27 14:40 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        String sqlReviewsQuery = "SELECT * FROM REVIEW WHERE REVIEW_ID = ?";
Убрал SELECT переписал по аналогии с другими классами

2023-05-27 14:40 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +            review = Review.builder().reviewId(updateSet.getInt("review_id")).content(updateSet.getString("content")).isPositive(updateSet.getBoolean("is_positive")).userId(updateSet.getLong("user_id
исправлено

2023-05-27 14:42 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +    public Collection<Review> getAllReviewsByFilmId(Long filmId, Integer count) {
Исправил

2023-05-27 14:43 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +
Исправил

2023-05-27 14:44 UTC, Nevisky commented on src/main/resources/schema.sql
> +    content varchar not null ,
Исправил

2023-05-27 14:59 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +            review = Review.builder().reviewId(updateSet.getInt("review_id")).content(updateSet.getString("content")).isPositive(updateSet.getBoolean("is_positive")).userId(updateSet.getLong("user_id
Исправил

2023-05-27 15:40 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +        if (review.getUserId() == null || review.getFilmId() == null) {
Вот тут как мне обработать ошибку, если userId и filmId отрицательные?

2023-05-27 20:59 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        return Review.builder().reviewId(rs.getLong("review_id")).content(rs.getString("content")).isPositive(rs.getBoolean("is_positive")).userId(rs.getLong("user_id")).filmId(rs.getLong("film_id"))
исправил

2023-05-27 21:39 UTC, vladislavStel approved these changes

2023-05-27 21:40 UTC, merged