add-common-films
vladislavStel/java-filmorate-team-project pull request #5
Opened 2023-05-25 23:59 UTC by Nevisky

Added new method:FindCommonFilmWithFriend

2023-05-26 10:28 UTC, vladislavStel requested changes

2023-05-26 10:28 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getCommonFilmsWithFriend(@RequestParam Long userId,
Предлагаю добавить аннотацию @Positive к userId и friendId для исключения отрицательного или нулевого Id

2023-05-26 10:28 UTC, vladislavStel commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    Collection<Film> getCommonFilms(Long userId, Long friendId);
Предлагаю использовать List вместо Collection

2023-05-27 21:29 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    Collection<Film> getCommonFilms(Long userId, Long friendId);
Исправил

2023-05-27 21:51 UTC, Nevisky commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getCommonFilmsWithFriend(@RequestParam Long userId,
Исправил

2023-05-28 13:51 UTC, vladislavStel approved these changes

2023-05-28 13:51 UTC, merged